// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace Ecommerce.Tests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Produtos do E-commerce")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class ProdutosDoE_CommerceFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("pt"), "Features", "Produtos do E-commerce", "  Como um usuário do e-commerce\r\n  Quero executar todos as ações possiveis\r\n  Par" +
                "a gerenciar meus produtos eficientemente\r\n  Ações: POST, GET, PUT, PATCH e DELET" +
                "E", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "Products.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Products.feature.ndjson", 8);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("a criação de um produto deve ser bem-sucedida")]
        [global::NUnit.Framework.CategoryAttribute("POST")]
        public async global::System.Threading.Tasks.Task ACriacaoDeUmProdutoDeveSerBem_Sucedida()
        {
            string[] tagsOfScenario = new string[] {
                    "POST"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("a criação de um produto deve ser bem-sucedida", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 10
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "Model",
                            "ReleaseDate",
                            "Specifications",
                            "Price",
                            "StockQuantity",
                            "Type"});
                table1.AddRow(new string[] {
                            "IPhone",
                            "2024-01-15",
                            "128GB, 6GB RAM",
                            "999.99",
                            "50",
                            "Smartphone"});
#line 11
 await testRunner.GivenAsync("que eu recebo um produto valido:", ((string)(null)), table1, "Dado ");
#line hidden
#line 14
 await testRunner.WhenAsync("eu envio uma requisição POST para \"/api/products\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 15
 await testRunner.ThenAsync("a resposta deve ter o código de status 201", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 16
 await testRunner.AndAsync("o corpo da resposta deve conter os detalhes do produto criado", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("a listagem de produtos deve ser bem-sucedida")]
        [global::NUnit.Framework.CategoryAttribute("GET")]
        public async global::System.Threading.Tasks.Task AListagemDeProdutosDeveSerBem_Sucedida()
        {
            string[] tagsOfScenario = new string[] {
                    "GET"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("a listagem de produtos deve ser bem-sucedida", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 19
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "Model",
                            "ReleaseDate",
                            "Specifications",
                            "Price",
                            "StockQuantity",
                            "Type"});
                table2.AddRow(new string[] {
                            "Pixel 6",
                            "2021-10-28",
                            "128GB, 8GB RAM",
                            "599.99",
                            "40",
                            "Smartphone"});
#line 20
 await testRunner.GivenAsync("que eu tenho produtos validos:", ((string)(null)), table2, "Dado ");
#line hidden
#line 23
 await testRunner.WhenAsync("eu envio uma requisição GET para \"/api/products\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 24
 await testRunner.ThenAsync("a resposta deve ter o código de status 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 25
 await testRunner.AndAsync("o corpo da resposta deve conter a lista de produtos cadastrados", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("a listagem de um produto específico deve ser bem-sucedida")]
        [global::NUnit.Framework.CategoryAttribute("GET")]
        public async global::System.Threading.Tasks.Task AListagemDeUmProdutoEspecificoDeveSerBem_Sucedida()
        {
            string[] tagsOfScenario = new string[] {
                    "GET"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("a listagem de um produto específico deve ser bem-sucedida", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 28
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                            "Model",
                            "ReleaseDate",
                            "Specifications",
                            "Price",
                            "StockQuantity",
                            "Type"});
                table3.AddRow(new string[] {
                            "Galaxy S21",
                            "2021-01-29",
                            "128GB, 8GB RAM",
                            "799.99",
                            "30",
                            "Smartphone"});
#line 29
 await testRunner.GivenAsync("que eu tenho um produto valido:", ((string)(null)), table3, "Dado ");
#line hidden
#line 32
 await testRunner.WhenAsync("eu envio uma requisição GET para \"/api/products/<id>\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 33
 await testRunner.ThenAsync("a resposta deve ter o código de status 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 34
 await testRunner.AndAsync("o corpo da resposta deve conter os detalhes do produto cadastrado", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("a atualização completa de um produto deve ser bem-sucedida")]
        [global::NUnit.Framework.CategoryAttribute("UPDATE")]
        public async global::System.Threading.Tasks.Task AAtualizacaoCompletaDeUmProdutoDeveSerBem_Sucedida()
        {
            string[] tagsOfScenario = new string[] {
                    "UPDATE"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("a atualização completa de um produto deve ser bem-sucedida", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 37
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "Model",
                            "ReleaseDate",
                            "Specifications",
                            "Price",
                            "StockQuantity",
                            "Type"});
                table4.AddRow(new string[] {
                            "Moto G",
                            "2020-02-20",
                            "64GB, 4GB RAM",
                            "299.99",
                            "20",
                            "Smartphone"});
#line 38
 await testRunner.GivenAsync("que eu tenho um produto valido:", ((string)(null)), table4, "Dado ");
#line hidden
                global::Reqnroll.Table table5 = new global::Reqnroll.Table(new string[] {
                            "Model",
                            "ReleaseDate",
                            "Specifications",
                            "Price",
                            "StockQuantity",
                            "Type"});
                table5.AddRow(new string[] {
                            "Edit",
                            "2020-02-20",
                            "64GB, 4GB RAM",
                            "99.99",
                            "20",
                            "Smartphone"});
#line 41
 await testRunner.AndAsync("eu recebo os novos dados do produto:", ((string)(null)), table5, "E ");
#line hidden
#line 44
 await testRunner.WhenAsync("eu envio uma requisição PUT para \"/api/products/<id>\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 45
 await testRunner.ThenAsync("a resposta deve ter o código de status 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 46
 await testRunner.AndAsync("o corpo da resposta deve conter os detalhes atualizados do produto", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("a atualização parcial de um produto deve ser bem-sucedida")]
        [global::NUnit.Framework.CategoryAttribute("UPDATE")]
        public async global::System.Threading.Tasks.Task AAtualizacaoParcialDeUmProdutoDeveSerBem_Sucedida()
        {
            string[] tagsOfScenario = new string[] {
                    "UPDATE"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("a atualização parcial de um produto deve ser bem-sucedida", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 49
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table6 = new global::Reqnroll.Table(new string[] {
                            "Model",
                            "ReleaseDate",
                            "Specifications",
                            "Price",
                            "StockQuantity",
                            "Type"});
                table6.AddRow(new string[] {
                            "Iphone SE",
                            "2020-04-24",
                            "64GB, 3GB RAM",
                            "399.99",
                            "15",
                            "Smartphone"});
#line 50
 await testRunner.GivenAsync("que eu tenho um produto valido:", ((string)(null)), table6, "Dado ");
#line hidden
#line 53
 await testRunner.AndAsync("que eu recebo as operações de atualização:", "[\r\n  { \"op\": \"replace\", \"path\": \"/price\", \"value\": 99.99 },\r\n  { \"op\": \"replace\"," +
                        " \"path\": \"/stockQuantity\", \"value\": 3 }\r\n]", ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 60
 await testRunner.WhenAsync("eu envio a requisição PATCH para \"api/products/<id>\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 61
 await testRunner.ThenAsync("a resposta deve ter o código de status 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 62
 await testRunner.AndAsync("o corpo da resposta deve conter os campos atualizados do produto", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("a exclusão de um produto deve ser bem-sucedida")]
        [global::NUnit.Framework.CategoryAttribute("DELETE")]
        public async global::System.Threading.Tasks.Task AExclusaoDeUmProdutoDeveSerBem_Sucedida()
        {
            string[] tagsOfScenario = new string[] {
                    "DELETE"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("a exclusão de um produto deve ser bem-sucedida", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 65
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table7 = new global::Reqnroll.Table(new string[] {
                            "Model",
                            "ReleaseDate",
                            "Specifications",
                            "Price",
                            "StockQuantity",
                            "Type"});
                table7.AddRow(new string[] {
                            "Nokia 3310",
                            "2000-09-01",
                            "16MB, 16MB RAM",
                            "349.99",
                            "100",
                            "Smartphone"});
#line 66
 await testRunner.GivenAsync("que eu tenho um produto valido:", ((string)(null)), table7, "Dado ");
#line hidden
#line 69
 await testRunner.WhenAsync("eu envio a requisição DELETE para \"api/products/<id>\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 70
 await testRunner.ThenAsync("a resposta deve ter o código de status 204", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 71
 await testRunner.AndAsync("ao tentar obter o produto excluído, a resposta deve ter o código de status 404", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
